In [1]:
import pandas as pd

prelim_venue_data = pd.read_csv('Output/summary_table.csv')

In [3]:
ny_venue_data = prelim_venue_data[(prelim_venue_data['Venue State']=='New York') | (prelim_venue_data['Venue State']=='NY')]
ny_venue_data['Venue State'].replace(to_replace='New York', value = 'NY', inplace=True)
delta = prelim_venue_data.shape[0] - ny_venue_data.shape[0]
print (f'{delta} entries were removed from the preliminary dataset based on "Venue State"')
ny_venue_data.head()

19 entries were removed from the preliminary dataset based on "Venue State"

/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue Name,Venue ID,Venue Category,Venue Latitude,Venue Longitude,Venue City,Venue State
0,Wakefield,40.894705,-73.847201,The Upper Room,4f57ef61e4b063a4ab675858,Music Venue,40.892567,-73.846406,NaN,NY
1,Wakefield,40.894705,-73.847201,241st Liquor Store,4f349b15e4b0e4d04e99a428,Other Nightlife,40.902771,-73.849898,Bronx,NY
2,Wakefield,40.894705,-73.847201,Dyme Life Radio,4da63d645da3e8486b80546f,Music Venue,40.894541,-73.843266,Bronx,NY
3,Wakefield,40.894705,-73.847201,Par-City,4d23aea014f2b1f7740f68be,Music Venue,40.890211,-73.847002,Bronx,NY
4,Wakefield,40.894705,-73.847201,Tavern,4f32cf0919836c91c7fd025d,Bar,40.895898,-73.855731,Bronx,NY

In [4]:
ny_venue_data_with_city = ny_venue_data[(ny_venue_data['Venue City'] != "N/A")]
delta = ny_venue_data.shape[0] - ny_venue_data_with_city.shape[0]
print (f'{delta} entries were removed based on "Venue City"')
ny_venue_data_with_city.head()

0 entries were removed based on "Venue City"

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue Name,Venue ID,Venue Category,Venue Latitude,Venue Longitude,Venue City,Venue State
0,Wakefield,40.894705,-73.847201,The Upper Room,4f57ef61e4b063a4ab675858,Music Venue,40.892567,-73.846406,NaN,NY
1,Wakefield,40.894705,-73.847201,241st Liquor Store,4f349b15e4b0e4d04e99a428,Other Nightlife,40.902771,-73.849898,Bronx,NY
2,Wakefield,40.894705,-73.847201,Dyme Life Radio,4da63d645da3e8486b80546f,Music Venue,40.894541,-73.843266,Bronx,NY
3,Wakefield,40.894705,-73.847201,Par-City,4d23aea014f2b1f7740f68be,Music Venue,40.890211,-73.847002,Bronx,NY
4,Wakefield,40.894705,-73.847201,Tavern,4f32cf0919836c91c7fd025d,Bar,40.895898,-73.855731,Bronx,NY

In [5]:
music_related_categories = ['Music Venue', 'Lounge', 'Nightclub', 'Jazz Club', 'Recording Studio', 'Piano Bar', 'Record Shop', 'Concert Hall', 'Kareoke Bar', 'Rock Club', 'Amphitheater', 'Music Festival', 'Opera House', 'Music School']
ny_music_venues = ny_venue_data_with_city[ny_venue_data_with_city['Venue Category'].isin(music_related_categories)]
delta = ny_venue_data_with_city.shape[0] - ny_music_venues.shape[0]
print (f'{delta} entries were removed based on "Venue Category" not being related to music')
print (ny_music_venues['Venue Category'].unique())
ny_music_venues.head()

7001 entries were removed based on "Venue Category" not being related to music
['Music Venue' 'Nightclub' 'Lounge' 'Jazz Club' 'Piano Bar' 'Concert Hall'
 'Rock Club' 'Amphitheater' 'Music Festival' 'Record Shop' 'Opera House'
 'Recording Studio' 'Music School']

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue Name,Venue ID,Venue Category,Venue Latitude,Venue Longitude,Venue City,Venue State
0,Wakefield,40.894705,-73.847201,The Upper Room,4f57ef61e4b063a4ab675858,Music Venue,40.892567,-73.846406,NaN,NY
2,Wakefield,40.894705,-73.847201,Dyme Life Radio,4da63d645da3e8486b80546f,Music Venue,40.894541,-73.843266,Bronx,NY
3,Wakefield,40.894705,-73.847201,Par-City,4d23aea014f2b1f7740f68be,Music Venue,40.890211,-73.847002,Bronx,NY
7,Wakefield,40.894705,-73.847201,MY Studio,4e9cb64c49017c00c840e759,Music Venue,40.901926,-73.853504,NaN,NY
8,Wakefield,40.894705,-73.847201,Major League Music Group,4ee0764f0aafbb3dbab41e92,Music Venue,40.891367,-73.850088,NaN,NY

In [10]:
len(ny_music_venues['Venue ID'].unique())

1226

In [ ]:
ny_music_venues.to_csv("Output/cleaned_venue_data2.csv")